name: Build ZMK firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build.yml@main
    with:
      board: seeeduino_xiao_ble
      shield: xiao60
